application: [YOUR_APP_ID_GOES_HERE]
version: 1
runtime: go
api_version: go1.9

handlers:

- url: /static
  static_dir: static

- url: /.*
  script: _go_app

skip_files:
 - tests/
 - client/
 - vendor/

env_variables:
  IGWEB_APP_ROOT: './'
